Milestone3
evansinho/React-Bookstore pull request #4
Opened 2020-08-11 15:00 UTC by addod19

## In this milestone, we performed the following actions:

- Make the BooksForm component stateful
    - The component should store the title and the book category in its own state
    - The component should implement the handleChange method which reacts to the user typing to input a name or to changes in the category select
    - Each change to the form should modify the component’s state
    - The component should implement handleSubmit which will save the new book in the Redux store and resets the component’s state

- Connect the REMOVE_BOOK action to the component
    - Add a new table column to the BooksList component. It should render the “Remove Book” button next to each book
    - Implement the handleRemoveBook method which accepts a book as an argument and removes it from the Redux store

2020-08-11 19:54 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-08-11 19:54 UTC, bellom commented on .eslintrc.json
> +  "parser": "babel-eslint",
Opps, we have some little changes in this file, check out the [microverse-linter-config](https://github.com/microverseinc/linters-config/tree/master/react-redux/.eslintrc.json)
![image](https://user-images.githubusercontent.com/31897434/73417568-ca44bd00-4318-11ea-8a5e-fedabd629b8c.png)
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

2020-08-11 19:54 UTC, bellom commented on src/actions/index.js
> +// });
It’s better to delete commented code. If you need to review a previous version of your code, use git history. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2020-08-11 19:54 UTC, bellom commented on src/constant/initialState.js
> +export default INITIAL_STATE;
I will advise you to always drop a note if you make any changes to the previous milestone requirement.
Creating a new file for this doesn't look bad. 👍

2020-08-12 14:05 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-08-12 14:17 UTC, merged